### ISSUE TITLE
Unknown command 'task-get'

### ISSUE THREAD

**Issue by chevcheli0s** [ptarmiganlabs/ctrl-q#120]
### What version of Ctrl-Q are you using?

3.2.0

### What command did you use to start Ctrl-Q?

./ctrl-q task-get --help

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2022-November sp1

### Describe the Bug

There is no option `task-get`. I tried different versions.
I also tried windows version.
![image](https://user-images.githubusercontent.com/48658076/213987364-086c7042-889f-4d87-ba7a-6e697bf192b6.png)

**Comment by mountaindude** [comment]
Duh. 

The documentation is updated wrt Ctrl-Q 3.3, which is due out very soon.
It's been 90% ready for some time, then some feature creep kicked in and the release was delayed.

I didn't mean to push out the docs, that was a mistake on my part. Sorry.
Please pretend that the "task-get" command doesn't exist... yet.

The new features in 3.3 will largely be around reload tasks.  
Possible to export all/some tasks as a task tree or table, as JSON file or Excel. 

Adding to the export it will also be possible to do bulk **import** of tasks from CSV or Excel.
This can simplify things immensely if you need to create lots of reload tasks, maybe when setting up a new Sense environment. 
Version 3.3 will have a set of basic task import features, if/when needed we can then enhance these as needed.

**Comment by mountaindude** [comment]
@chevcheli0s 

Version [3.4.1](https://github.com/ptarmiganlabs/ctrl-q/releases/tag/ctrl-q-v3.4.1) was just released, and the readme updated accordingly. 
Feel free to give it a try :)
