### ISSUE TITLE
app-import failing while retrieving server tags

### ISSUE THREAD

**Issue by youritorchalski** [ptarmiganlabs/ctrl-q#382]
### What version of Ctrl-Q are you using?

3.15.0

### What command did you use to start Ctrl-Q?

see screenshot as the secure information is blurred 

### What operating system are you using?

MS Windows Server 2019 Std

### What CPU architecture are you using?

x64

### What Qlik Sense versions are you using?

May 2023 patch 8 (14.129.15)

### Describe the Bug

It happens with both JWT and cert authentication:
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/46277002/4c02e81b-184f-493f-a216-4c259ef5ba3d)

![image](https://github.com/ptarmiganlabs/ctrl-q/assets/46277002/905ae012-68eb-4103-ae99-51de88b186fe)

### Expected Behavior

Apps are being imported

**Comment by youritorchalski** [comment]
Any update on this @mountaindude?

**Comment by mountaindude** [comment]
Have not had a chance to look into this in detail yet.
Looks like you might have a "https" too much though..

The getaddrinfo error indicate that you are using https://10.11.12.13/foo/bar when you should just be using 10.11.12.13/foo/bar.
Or whatever IP/path you are using.
That's just a very quick guess though.

**Comment by mountaindude** [comment]
The Ctrl-Q site has [examples](https://ctrl-q.ptarmiganlabs.com/docs/command/import/app/#import-apps-from-qvf-files) on what the `--host` option should look like. 
Could it be that you included "https://" there...?

**Comment by youritorchalski** [comment]
I have https:// in it yes. That must be it. I will tesr and come back to you. Thanks for responding.

Kind regards,


Youri Torchalski
Business Intelligence Consultant Qlik

Sent from a mobile device



________________________________
Van: Göran Sander ***@***.***>
Verzonden: Tuesday, January 9, 2024 10:44:35 AM
Aan: ptarmiganlabs/ctrl-q ***@***.***>
CC: Youri Torchalski ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ptarmiganlabs/ctrl-q] app-import failing while retrieving server tags (Issue #382)


The Ctrl-Q site has examples<https://ctrl-q.ptarmiganlabs.com/docs/command/import/app/#import-apps-from-qvf-files> on what the --host option should look like.
Could it be that you included "https://" there...?
